package pojos;

// Generated Nov 29, 2012 10:41:24 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * BinhLuan generated by hbm2java
 */
public class BinhLuan implements java.io.Serializable
{

    private long maBinhLuan;
    private DoChoi doChoi;
    private TaiKhoan taiKhoan;
    private Date ngayBinhLuan;
    private String noiDung;
    private boolean kiemDuyet;
    private boolean daXoa;

    public BinhLuan()
    {
    }

    public BinhLuan(long maBinhLuan, DoChoi doChoi, TaiKhoan taiKhoan,
            Date ngayBinhLuan, String noiDung, boolean kiemDuyet, boolean daXoa)
    {
        this.maBinhLuan = maBinhLuan;
        this.doChoi = doChoi;
        this.taiKhoan = taiKhoan;
        this.ngayBinhLuan = ngayBinhLuan;
        this.noiDung = noiDung;
        this.kiemDuyet = kiemDuyet;
        this.daXoa = daXoa;
    }

    public long getMaBinhLuan()
    {
        return this.maBinhLuan;
    }

    public void setMaBinhLuan(long maBinhLuan)
    {
        this.maBinhLuan = maBinhLuan;
    }

    public DoChoi getDoChoi()
    {
        return this.doChoi;
    }

    public void setDoChoi(DoChoi doChoi)
    {
        this.doChoi = doChoi;
    }

    public TaiKhoan getTaiKhoan()
    {
        return this.taiKhoan;
    }

    public void setTaiKhoan(TaiKhoan taiKhoan)
    {
        this.taiKhoan = taiKhoan;
    }

    public Date getNgayBinhLuan()
    {
        return this.ngayBinhLuan;
    }

    public void setNgayBinhLuan(Date ngayBinhLuan)
    {
        this.ngayBinhLuan = ngayBinhLuan;
    }

    public String getNoiDung()
    {
        return this.noiDung;
    }

    public void setNoiDung(String noiDung)
    {
        this.noiDung = noiDung;
    }

    public boolean isKiemDuyet()
    {
        return this.kiemDuyet;
    }

    public void setKiemDuyet(boolean kiemDuyet)
    {
        this.kiemDuyet = kiemDuyet;
    }

    public boolean isDaXoa()
    {
        return this.daXoa;
    }

    public void setDaXoa(boolean daXoa)
    {
        this.daXoa = daXoa;
    }

}
