package pojos;

// Generated Nov 29, 2012 10:41:24 AM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DoChoi generated by hbm2java
 */
public class DoChoi implements java.io.Serializable
{

    private long maDoChoi;
    private LoaiDoChoi loaiDoChoi;
    private NhaSanXuat nhaSanXuat;
    private XuatXu xuatXu;
    private String tenDoChoi;
    private String hinhAnhHienThiChinh;
    private String moTa;
    private BigDecimal giaBanBanDau;
    private BigDecimal giaBanHienTai;
    private Integer soLuongBan;
    private Integer soLuongXem;
    private String tinhTrang;
    private Integer giamGia;
    private Date ngayTiepNhan;
    private Integer soLuongTon;
    private Integer soLuongDaBan;
    private Date ngayCapNhat;
    private boolean daXoa;
    private Set<TuKhoaDoChoi> tuKhoaDoChois = new HashSet<TuKhoaDoChoi>(0);
    private Set<ChiTietHoaDon> chiTietHoaDons = new HashSet<ChiTietHoaDon>(0);
    private Set<BinhLuan> binhLuans = new HashSet<BinhLuan>(0);
    private Set<HinhAnhDoChoi> hinhAnhDoChois = new HashSet<HinhAnhDoChoi>(0);

    public DoChoi()
    {
    }

    public DoChoi(long maDoChoi, boolean daXoa)
    {
        this.maDoChoi = maDoChoi;
        this.daXoa = daXoa;
    }

    public DoChoi(long maDoChoi, LoaiDoChoi loaiDoChoi, NhaSanXuat nhaSanXuat,
            XuatXu xuatXu, String tenDoChoi, String hinhAnhHienThiChinh,
            String moTa, BigDecimal giaBanBanDau, BigDecimal giaBanHienTai,
            Integer soLuongBan, Integer soLuongXem, String tinhTrang,
            Integer giamGia, Date ngayTiepNhan, Integer soLuongTon,
            Integer soLuongDaBan, Date ngayCapNhat, boolean daXoa,
            Set<TuKhoaDoChoi> tuKhoaDoChois, Set<ChiTietHoaDon> chiTietHoaDons,
            Set<BinhLuan> binhLuans, Set<HinhAnhDoChoi> hinhAnhDoChois)
    {
        this.maDoChoi = maDoChoi;
        this.loaiDoChoi = loaiDoChoi;
        this.nhaSanXuat = nhaSanXuat;
        this.xuatXu = xuatXu;
        this.tenDoChoi = tenDoChoi;
        this.hinhAnhHienThiChinh = hinhAnhHienThiChinh;
        this.moTa = moTa;
        this.giaBanBanDau = giaBanBanDau;
        this.giaBanHienTai = giaBanHienTai;
        this.soLuongBan = soLuongBan;
        this.soLuongXem = soLuongXem;
        this.tinhTrang = tinhTrang;
        this.giamGia = giamGia;
        this.ngayTiepNhan = ngayTiepNhan;
        this.soLuongTon = soLuongTon;
        this.soLuongDaBan = soLuongDaBan;
        this.ngayCapNhat = ngayCapNhat;
        this.daXoa = daXoa;
        this.tuKhoaDoChois = tuKhoaDoChois;
        this.chiTietHoaDons = chiTietHoaDons;
        this.binhLuans = binhLuans;
        this.hinhAnhDoChois = hinhAnhDoChois;
    }

    public long getMaDoChoi()
    {
        return this.maDoChoi;
    }

    public void setMaDoChoi(long maDoChoi)
    {
        this.maDoChoi = maDoChoi;
    }

    public LoaiDoChoi getLoaiDoChoi()
    {
        return this.loaiDoChoi;
    }

    public void setLoaiDoChoi(LoaiDoChoi loaiDoChoi)
    {
        this.loaiDoChoi = loaiDoChoi;
    }

    public NhaSanXuat getNhaSanXuat()
    {
        return this.nhaSanXuat;
    }

    public void setNhaSanXuat(NhaSanXuat nhaSanXuat)
    {
        this.nhaSanXuat = nhaSanXuat;
    }

    public XuatXu getXuatXu()
    {
        return this.xuatXu;
    }

    public void setXuatXu(XuatXu xuatXu)
    {
        this.xuatXu = xuatXu;
    }

    public String getTenDoChoi()
    {
        return this.tenDoChoi;
    }

    public void setTenDoChoi(String tenDoChoi)
    {
        this.tenDoChoi = tenDoChoi;
    }

    public String getHinhAnhHienThiChinh()
    {
        return this.hinhAnhHienThiChinh;
    }

    public void setHinhAnhHienThiChinh(String hinhAnhHienThiChinh)
    {
        this.hinhAnhHienThiChinh = hinhAnhHienThiChinh;
    }

    public String getMoTa()
    {
        return this.moTa;
    }

    public void setMoTa(String moTa)
    {
        this.moTa = moTa;
    }

    public BigDecimal getGiaBanBanDau()
    {
        return this.giaBanBanDau;
    }

    public void setGiaBanBanDau(BigDecimal giaBanBanDau)
    {
        this.giaBanBanDau = giaBanBanDau;
    }

    public BigDecimal getGiaBanHienTai()
    {
        return this.giaBanHienTai;
    }

    public void setGiaBanHienTai(BigDecimal giaBanHienTai)
    {
        this.giaBanHienTai = giaBanHienTai;
    }

    public Integer getSoLuongBan()
    {
        return this.soLuongBan;
    }

    public void setSoLuongBan(Integer soLuongBan)
    {
        this.soLuongBan = soLuongBan;
    }

    public Integer getSoLuongXem()
    {
        return this.soLuongXem;
    }

    public void setSoLuongXem(Integer soLuongXem)
    {
        this.soLuongXem = soLuongXem;
    }

    public String getTinhTrang()
    {
        return this.tinhTrang;
    }

    public void setTinhTrang(String tinhTrang)
    {
        this.tinhTrang = tinhTrang;
    }

    public Integer getGiamGia()
    {
        return this.giamGia;
    }

    public void setGiamGia(Integer giamGia)
    {
        this.giamGia = giamGia;
    }

    public Date getNgayTiepNhan()
    {
        return this.ngayTiepNhan;
    }

    public void setNgayTiepNhan(Date ngayTiepNhan)
    {
        this.ngayTiepNhan = ngayTiepNhan;
    }

    public Integer getSoLuongTon()
    {
        return this.soLuongTon;
    }

    public void setSoLuongTon(Integer soLuongTon)
    {
        this.soLuongTon = soLuongTon;
    }

    public Integer getSoLuongDaBan()
    {
        return this.soLuongDaBan;
    }

    public void setSoLuongDaBan(Integer soLuongDaBan)
    {
        this.soLuongDaBan = soLuongDaBan;
    }

    public Date getNgayCapNhat()
    {
        return this.ngayCapNhat;
    }

    public void setNgayCapNhat(Date ngayCapNhat)
    {
        this.ngayCapNhat = ngayCapNhat;
    }

    public boolean isDaXoa()
    {
        return this.daXoa;
    }

    public void setDaXoa(boolean daXoa)
    {
        this.daXoa = daXoa;
    }

    public Set<TuKhoaDoChoi> getTuKhoaDoChois()
    {
        return this.tuKhoaDoChois;
    }

    public void setTuKhoaDoChois(Set<TuKhoaDoChoi> tuKhoaDoChois)
    {
        this.tuKhoaDoChois = tuKhoaDoChois;
    }

    public Set<ChiTietHoaDon> getChiTietHoaDons()
    {
        return this.chiTietHoaDons;
    }

    public void setChiTietHoaDons(Set<ChiTietHoaDon> chiTietHoaDons)
    {
        this.chiTietHoaDons = chiTietHoaDons;
    }

    public Set<BinhLuan> getBinhLuans()
    {
        return this.binhLuans;
    }

    public void setBinhLuans(Set<BinhLuan> binhLuans)
    {
        this.binhLuans = binhLuans;
    }

    public Set<HinhAnhDoChoi> getHinhAnhDoChois()
    {
        return this.hinhAnhDoChois;
    }

    public void setHinhAnhDoChois(Set<HinhAnhDoChoi> hinhAnhDoChois)
    {
        this.hinhAnhDoChois = hinhAnhDoChois;
    }

}
