package pojos;

// Generated Nov 29, 2012 10:41:24 AM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * HoaDon generated by hbm2java
 */
public class HoaDon implements java.io.Serializable
{

    private long maHoaDon;
    private TaiKhoan taiKhoan;
    private TrangThaiDonHang trangThaiDonHang;
    private Date ngayLap;
    private String tenKhachHang;
    private String diaChiGiaoHang;
    private BigDecimal tongTien;
    private Date ngayCapNhat;
    private Boolean daThanhToan;
    private boolean daXoa;
    private Set<ChiTietHoaDon> chiTietHoaDons = new HashSet<ChiTietHoaDon>(0);

    public HoaDon()
    {
    }

    public HoaDon(long maHoaDon, TaiKhoan taiKhoan,
            TrangThaiDonHang trangThaiDonHang, Date ngayLap,
            String tenKhachHang, String diaChiGiaoHang, boolean daXoa)
    {
        this.maHoaDon = maHoaDon;
        this.taiKhoan = taiKhoan;
        this.trangThaiDonHang = trangThaiDonHang;
        this.ngayLap = ngayLap;
        this.tenKhachHang = tenKhachHang;
        this.diaChiGiaoHang = diaChiGiaoHang;
        this.daXoa = daXoa;
    }

    public HoaDon(long maHoaDon, TaiKhoan taiKhoan,
            TrangThaiDonHang trangThaiDonHang, Date ngayLap,
            String tenKhachHang, String diaChiGiaoHang, BigDecimal tongTien,
            Date ngayCapNhat, Boolean daThanhToan, boolean daXoa,
            Set<ChiTietHoaDon> chiTietHoaDons)
    {
        this.maHoaDon = maHoaDon;
        this.taiKhoan = taiKhoan;
        this.trangThaiDonHang = trangThaiDonHang;
        this.ngayLap = ngayLap;
        this.tenKhachHang = tenKhachHang;
        this.diaChiGiaoHang = diaChiGiaoHang;
        this.tongTien = tongTien;
        this.ngayCapNhat = ngayCapNhat;
        this.daThanhToan = daThanhToan;
        this.daXoa = daXoa;
        this.chiTietHoaDons = chiTietHoaDons;
    }

    public long getMaHoaDon()
    {
        return this.maHoaDon;
    }

    public void setMaHoaDon(long maHoaDon)
    {
        this.maHoaDon = maHoaDon;
    }

    public TaiKhoan getTaiKhoan()
    {
        return this.taiKhoan;
    }

    public void setTaiKhoan(TaiKhoan taiKhoan)
    {
        this.taiKhoan = taiKhoan;
    }

    public TrangThaiDonHang getTrangThaiDonHang()
    {
        return this.trangThaiDonHang;
    }

    public void setTrangThaiDonHang(TrangThaiDonHang trangThaiDonHang)
    {
        this.trangThaiDonHang = trangThaiDonHang;
    }

    public Date getNgayLap()
    {
        return this.ngayLap;
    }

    public void setNgayLap(Date ngayLap)
    {
        this.ngayLap = ngayLap;
    }

    public String getTenKhachHang()
    {
        return this.tenKhachHang;
    }

    public void setTenKhachHang(String tenKhachHang)
    {
        this.tenKhachHang = tenKhachHang;
    }

    public String getDiaChiGiaoHang()
    {
        return this.diaChiGiaoHang;
    }

    public void setDiaChiGiaoHang(String diaChiGiaoHang)
    {
        this.diaChiGiaoHang = diaChiGiaoHang;
    }

    public BigDecimal getTongTien()
    {
        return this.tongTien;
    }

    public void setTongTien(BigDecimal tongTien)
    {
        this.tongTien = tongTien;
    }

    public Date getNgayCapNhat()
    {
        return this.ngayCapNhat;
    }

    public void setNgayCapNhat(Date ngayCapNhat)
    {
        this.ngayCapNhat = ngayCapNhat;
    }

    public Boolean getDaThanhToan()
    {
        return this.daThanhToan;
    }

    public void setDaThanhToan(Boolean daThanhToan)
    {
        this.daThanhToan = daThanhToan;
    }

    public boolean isDaXoa()
    {
        return this.daXoa;
    }

    public void setDaXoa(boolean daXoa)
    {
        this.daXoa = daXoa;
    }

    public Set<ChiTietHoaDon> getChiTietHoaDons()
    {
        return this.chiTietHoaDons;
    }

    public void setChiTietHoaDons(Set<ChiTietHoaDon> chiTietHoaDons)
    {
        this.chiTietHoaDons = chiTietHoaDons;
    }

}
