package pojos;

// Generated Nov 29, 2012 10:41:24 AM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * NhaSanXuat generated by hbm2java
 */
public class NhaSanXuat implements java.io.Serializable
{

    private long maNhaSanXuat;
    private String tenNhaSanXuat;
    private Date ngayCapNhat;
    private boolean daXoa;
    private Set<DoChoi> doChois = new HashSet<DoChoi>(0);

    public NhaSanXuat()
    {
    }

    public NhaSanXuat(long maNhaSanXuat, String tenNhaSanXuat, boolean daXoa)
    {
        this.maNhaSanXuat = maNhaSanXuat;
        this.tenNhaSanXuat = tenNhaSanXuat;
        this.daXoa = daXoa;
    }

    public NhaSanXuat(long maNhaSanXuat, String tenNhaSanXuat,
            Date ngayCapNhat, boolean daXoa, Set<DoChoi> doChois)
    {
        this.maNhaSanXuat = maNhaSanXuat;
        this.tenNhaSanXuat = tenNhaSanXuat;
        this.ngayCapNhat = ngayCapNhat;
        this.daXoa = daXoa;
        this.doChois = doChois;
    }

    public long getMaNhaSanXuat()
    {
        return this.maNhaSanXuat;
    }

    public void setMaNhaSanXuat(long maNhaSanXuat)
    {
        this.maNhaSanXuat = maNhaSanXuat;
    }

    public String getTenNhaSanXuat()
    {
        return this.tenNhaSanXuat;
    }

    public void setTenNhaSanXuat(String tenNhaSanXuat)
    {
        this.tenNhaSanXuat = tenNhaSanXuat;
    }

    public Date getNgayCapNhat()
    {
        return this.ngayCapNhat;
    }

    public void setNgayCapNhat(Date ngayCapNhat)
    {
        this.ngayCapNhat = ngayCapNhat;
    }

    public boolean isDaXoa()
    {
        return this.daXoa;
    }

    public void setDaXoa(boolean daXoa)
    {
        this.daXoa = daXoa;
    }

    public Set<DoChoi> getDoChois()
    {
        return this.doChois;
    }

    public void setDoChois(Set<DoChoi> doChois)
    {
        this.doChois = doChois;
    }

}
