package pojos;

// Generated Nov 29, 2012 10:41:24 AM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TaiKhoan generated by hbm2java
 */
public class TaiKhoan implements java.io.Serializable
{

    private String maTaiKhoan;
    private LoaiTaiKhoan loaiTaiKhoan;
    private String matKhau;
    private String avatar;
    private String hoTen;
    private Date ngaySinh;
    private String thanhPho;
    private String dienThoai;
    private Boolean gioiTinh;
    private String email;
    private Date ngayCapNhat;
    private Boolean daXoa;
    private Boolean daBan;
    private Set<BinhLuan> binhLuans = new HashSet<BinhLuan>(0);
    private Set<HoaDon> hoaDons = new HashSet<HoaDon>(0);

    public TaiKhoan()
    {
    }

    public TaiKhoan(String maTaiKhoan, LoaiTaiKhoan loaiTaiKhoan, String matKhau)
    {
        this.maTaiKhoan = maTaiKhoan;
        this.loaiTaiKhoan = loaiTaiKhoan;
        this.matKhau = matKhau;
    }

    public TaiKhoan(String maTaiKhoan, LoaiTaiKhoan loaiTaiKhoan,
            String matKhau, String avatar, String hoTen, Date ngaySinh,
            String thanhPho, String dienThoai, Boolean gioiTinh, String email,
            Date ngayCapNhat, Boolean daXoa, Boolean daBan, Set<BinhLuan> binhLuans,
            Set<HoaDon> hoaDons)
    {
        this.maTaiKhoan = maTaiKhoan;
        this.loaiTaiKhoan = loaiTaiKhoan;
        this.matKhau = matKhau;
        this.avatar = avatar;
        this.hoTen = hoTen;
        this.ngaySinh = ngaySinh;
        this.thanhPho = thanhPho;
        this.dienThoai = dienThoai;
        this.gioiTinh = gioiTinh;
        this.email = email;
        this.ngayCapNhat = ngayCapNhat;
        this.daXoa = daXoa;
        this.daBan = daBan;
        this.binhLuans = binhLuans;
        this.hoaDons = hoaDons;
    }

    public String getMaTaiKhoan()
    {
        return this.maTaiKhoan;
    }

    public void setMaTaiKhoan(String maTaiKhoan)
    {
        this.maTaiKhoan = maTaiKhoan;
    }

    public LoaiTaiKhoan getLoaiTaiKhoan()
    {
        return this.loaiTaiKhoan;
    }

    public void setLoaiTaiKhoan(LoaiTaiKhoan loaiTaiKhoan)
    {
        this.loaiTaiKhoan = loaiTaiKhoan;
    }

    public String getMatKhau()
    {
        return this.matKhau;
    }

    public void setMatKhau(String matKhau)
    {
        this.matKhau = matKhau;
    }

    public String getAvatar()
    {
        return this.avatar;
    }

    public void setAvatar(String avatar)
    {
        this.avatar = avatar;
    }

    public String getHoTen()
    {
        return this.hoTen;
    }

    public void setHoTen(String hoTen)
    {
        this.hoTen = hoTen;
    }

    public Date getNgaySinh()
    {
        return this.ngaySinh;
    }

    public void setNgaySinh(Date ngaySinh)
    {
        this.ngaySinh = ngaySinh;
    }

    public String getThanhPho()
    {
        return this.thanhPho;
    }

    public void setThanhPho(String thanhPho)
    {
        this.thanhPho = thanhPho;
    }

    public String getDienThoai()
    {
        return this.dienThoai;
    }

    public void setDienThoai(String dienThoai)
    {
        this.dienThoai = dienThoai;
    }

    public Boolean getGioiTinh()
    {
        return this.gioiTinh;
    }

    public void setGioiTinh(Boolean gioiTinh)
    {
        this.gioiTinh = gioiTinh;
    }

    public String getEmail()
    {
        return this.email;
    }

    public void setEmail(String email)
    {
        this.email = email;
    }

    public Date getNgayCapNhat()
    {
        return this.ngayCapNhat;
    }

    public void setNgayCapNhat(Date ngayCapNhat)
    {
        this.ngayCapNhat = ngayCapNhat;
    }

    public Boolean getDaXoa()
    {
        return this.daXoa;
    }

    public void setDaXoa(Boolean daXoa)
    {
        this.daXoa = daXoa;
    }
    
    public Boolean getDaBan() {
        return this.daBan;
    }
    
    public void setDaBan(Boolean daBan) {
        this.daBan = daBan;
    }
    
    public Set<BinhLuan> getBinhLuans()
    {
        return this.binhLuans;
    }

    public void setBinhLuans(Set<BinhLuan> binhLuans)
    {
        this.binhLuans = binhLuans;
    }

    public Set<HoaDon> getHoaDons()
    {
        return this.hoaDons;
    }

    public void setHoaDons(Set<HoaDon> hoaDons)
    {
        this.hoaDons = hoaDons;
    }

}
