package pojos;

// Generated Nov 29, 2012 10:41:24 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * TrangThaiDonHang generated by hbm2java
 */
public class TrangThaiDonHang implements java.io.Serializable
{

    private long maTrangThaiDonHang;
    private String tenTrangThaiDonHang;
    private Set<HoaDon> hoaDons = new HashSet<HoaDon>(0);

    public TrangThaiDonHang()
    {
    }

    public TrangThaiDonHang(long maTrangThaiDonHang, String tenTrangThaiDonHang)
    {
        this.maTrangThaiDonHang = maTrangThaiDonHang;
        this.tenTrangThaiDonHang = tenTrangThaiDonHang;
    }

    public TrangThaiDonHang(long maTrangThaiDonHang,
            String tenTrangThaiDonHang, Set<HoaDon> hoaDons)
    {
        this.maTrangThaiDonHang = maTrangThaiDonHang;
        this.tenTrangThaiDonHang = tenTrangThaiDonHang;
        this.hoaDons = hoaDons;
    }

    public long getMaTrangThaiDonHang()
    {
        return this.maTrangThaiDonHang;
    }

    public void setMaTrangThaiDonHang(long maTrangThaiDonHang)
    {
        this.maTrangThaiDonHang = maTrangThaiDonHang;
    }

    public String getTenTrangThaiDonHang()
    {
        return this.tenTrangThaiDonHang;
    }

    public void setTenTrangThaiDonHang(String tenTrangThaiDonHang)
    {
        this.tenTrangThaiDonHang = tenTrangThaiDonHang;
    }

    public Set<HoaDon> getHoaDons()
    {
        return this.hoaDons;
    }

    public void setHoaDons(Set<HoaDon> hoaDons)
    {
        this.hoaDons = hoaDons;
    }

}
