package pojos;
// Generated Oct 30, 2012 9:28:39 PM by Hibernate Tools 3.2.1.GA



/**
 * HinhAnhDoChoi generated by hbm2java
 */
public class HinhAnhDoChoi  implements java.io.Serializable {


     private long maHinhAnh;
     private DoChoi doChoi;
     private String hinhAnh;
     private Boolean daXoa;

    public HinhAnhDoChoi() {
    }

	
    public HinhAnhDoChoi(long maHinhAnh) {
        this.maHinhAnh = maHinhAnh;
    }
    public HinhAnhDoChoi(long maHinhAnh, DoChoi doChoi, String hinhAnh, Boolean daXoa) {
       this.maHinhAnh = maHinhAnh;
       this.doChoi = doChoi;
       this.hinhAnh = hinhAnh;
       this.daXoa = daXoa;
    }
   
    public long getMaHinhAnh() {
        return this.maHinhAnh;
    }
    
    public void setMaHinhAnh(long maHinhAnh) {
        this.maHinhAnh = maHinhAnh;
    }
    public DoChoi getDoChoi() {
        return this.doChoi;
    }
    
    public void setDoChoi(DoChoi doChoi) {
        this.doChoi = doChoi;
    }
    public String getHinhAnh() {
        return this.hinhAnh;
    }
    
    public void setHinhAnh(String hinhAnh) {
        this.hinhAnh = hinhAnh;
    }
    public Boolean getDaXoa() {
        return this.daXoa;
    }
    
    public void setDaXoa(Boolean daXoa) {
        this.daXoa = daXoa;
    }




}


