package pojos;
// Generated Oct 30, 2012 9:28:39 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * NhaSanXuat generated by hbm2java
 */
public class NhaSanXuat  implements java.io.Serializable {


     private long maNhaSanXuat;
     private String tenNhaSanXuat;
     private Date ngayCapNhat;
     private boolean daXoa;
     private Set doChois = new HashSet(0);

    public NhaSanXuat() {
    }

	
    public NhaSanXuat(long maNhaSanXuat, String tenNhaSanXuat, boolean daXoa) {
        this.maNhaSanXuat = maNhaSanXuat;
        this.tenNhaSanXuat = tenNhaSanXuat;
        this.daXoa = daXoa;
    }
    public NhaSanXuat(long maNhaSanXuat, String tenNhaSanXuat, Date ngayCapNhat, boolean daXoa, Set doChois) {
       this.maNhaSanXuat = maNhaSanXuat;
       this.tenNhaSanXuat = tenNhaSanXuat;
       this.ngayCapNhat = ngayCapNhat;
       this.daXoa = daXoa;
       this.doChois = doChois;
    }
   
    public long getMaNhaSanXuat() {
        return this.maNhaSanXuat;
    }
    
    public void setMaNhaSanXuat(long maNhaSanXuat) {
        this.maNhaSanXuat = maNhaSanXuat;
    }
    public String getTenNhaSanXuat() {
        return this.tenNhaSanXuat;
    }
    
    public void setTenNhaSanXuat(String tenNhaSanXuat) {
        this.tenNhaSanXuat = tenNhaSanXuat;
    }
    public Date getNgayCapNhat() {
        return this.ngayCapNhat;
    }
    
    public void setNgayCapNhat(Date ngayCapNhat) {
        this.ngayCapNhat = ngayCapNhat;
    }
    public boolean isDaXoa() {
        return this.daXoa;
    }
    
    public void setDaXoa(boolean daXoa) {
        this.daXoa = daXoa;
    }
    public Set getDoChois() {
        return this.doChois;
    }
    
    public void setDoChois(Set doChois) {
        this.doChois = doChois;
    }




}


