package pojos;
// Generated Oct 30, 2012 9:28:39 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * LoaiTaiKhoan generated by hbm2java
 */
public class LoaiTaiKhoan  implements java.io.Serializable {


     private long maLoaiTaiKhoan;
     private String tenLoaiTaiKhoan;
     private Set taiKhoans = new HashSet(0);

    public LoaiTaiKhoan() {
    }

	
    public LoaiTaiKhoan(long maLoaiTaiKhoan) {
        this.maLoaiTaiKhoan = maLoaiTaiKhoan;
    }
    public LoaiTaiKhoan(long maLoaiTaiKhoan, String tenLoaiTaiKhoan, Set taiKhoans) {
       this.maLoaiTaiKhoan = maLoaiTaiKhoan;
       this.tenLoaiTaiKhoan = tenLoaiTaiKhoan;
       this.taiKhoans = taiKhoans;
    }
   
    public long getMaLoaiTaiKhoan() {
        return this.maLoaiTaiKhoan;
    }
    
    public void setMaLoaiTaiKhoan(long maLoaiTaiKhoan) {
        this.maLoaiTaiKhoan = maLoaiTaiKhoan;
    }
    public String getTenLoaiTaiKhoan() {
        return this.tenLoaiTaiKhoan;
    }
    
    public void setTenLoaiTaiKhoan(String tenLoaiTaiKhoan) {
        this.tenLoaiTaiKhoan = tenLoaiTaiKhoan;
    }
    public Set getTaiKhoans() {
        return this.taiKhoans;
    }
    
    public void setTaiKhoans(Set taiKhoans) {
        this.taiKhoans = taiKhoans;
    }




}


