package pojos;
// Generated Oct 30, 2012 9:28:39 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TrangThaiDonHang generated by hbm2java
 */
public class TrangThaiDonHang  implements java.io.Serializable {


     private long maTrangThaiDonHang;
     private String tenTrangThaiDonHang;
     private Set hoaDons = new HashSet(0);

    public TrangThaiDonHang() {
    }

	
    public TrangThaiDonHang(long maTrangThaiDonHang, String tenTrangThaiDonHang) {
        this.maTrangThaiDonHang = maTrangThaiDonHang;
        this.tenTrangThaiDonHang = tenTrangThaiDonHang;
    }
    public TrangThaiDonHang(long maTrangThaiDonHang, String tenTrangThaiDonHang, Set hoaDons) {
       this.maTrangThaiDonHang = maTrangThaiDonHang;
       this.tenTrangThaiDonHang = tenTrangThaiDonHang;
       this.hoaDons = hoaDons;
    }
   
    public long getMaTrangThaiDonHang() {
        return this.maTrangThaiDonHang;
    }
    
    public void setMaTrangThaiDonHang(long maTrangThaiDonHang) {
        this.maTrangThaiDonHang = maTrangThaiDonHang;
    }
    public String getTenTrangThaiDonHang() {
        return this.tenTrangThaiDonHang;
    }
    
    public void setTenTrangThaiDonHang(String tenTrangThaiDonHang) {
        this.tenTrangThaiDonHang = tenTrangThaiDonHang;
    }
    public Set getHoaDons() {
        return this.hoaDons;
    }
    
    public void setHoaDons(Set hoaDons) {
        this.hoaDons = hoaDons;
    }




}


