package pojos;

// Generated Nov 29, 2012 10:41:24 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * LoaiTaiKhoan generated by hbm2java
 */
public class LoaiTaiKhoan implements java.io.Serializable
{

    private long maLoaiTaiKhoan;
    private String tenLoaiTaiKhoan;
    private Set<TaiKhoan> taiKhoans = new HashSet<TaiKhoan>(0);

    public LoaiTaiKhoan()
    {
    }

    public LoaiTaiKhoan(long maLoaiTaiKhoan)
    {
        this.maLoaiTaiKhoan = maLoaiTaiKhoan;
    }

    public LoaiTaiKhoan(long maLoaiTaiKhoan, String tenLoaiTaiKhoan,
            Set<TaiKhoan> taiKhoans)
    {
        this.maLoaiTaiKhoan = maLoaiTaiKhoan;
        this.tenLoaiTaiKhoan = tenLoaiTaiKhoan;
        this.taiKhoans = taiKhoans;
    }

    public long getMaLoaiTaiKhoan()
    {
        return this.maLoaiTaiKhoan;
    }

    public void setMaLoaiTaiKhoan(long maLoaiTaiKhoan)
    {
        this.maLoaiTaiKhoan = maLoaiTaiKhoan;
    }

    public String getTenLoaiTaiKhoan()
    {
        return this.tenLoaiTaiKhoan;
    }

    public void setTenLoaiTaiKhoan(String tenLoaiTaiKhoan)
    {
        this.tenLoaiTaiKhoan = tenLoaiTaiKhoan;
    }

    public Set<TaiKhoan> getTaiKhoans()
    {
        return this.taiKhoans;
    }

    public void setTaiKhoans(Set<TaiKhoan> taiKhoans)
    {
        this.taiKhoans = taiKhoans;
    }

}
